language: rust
sudo: true
rust:
  - stable
  - beta
  - nightly
  - 1.17.0
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV=true
services:
  - redis-server
script:
  - cargo install --debug cargo-make
  - cargo make ci-flow
