language: rust
sudo: true
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - KCOV_VERSION=33
services:
  - redis-server
before_install:
  - sudo apt-get update
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
script:
  - cargo build --verbose
  - cargo test --verbose
  - echo "Running coverage"
  - wget https://github.com/SimonKagstrom/kcov/archive/v$KCOV_VERSION.zip
  - unzip v$KCOV_VERSION.zip
  - cd kcov-$KCOV_VERSION
  - mkdir build
  - cd ./build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - rm -rf kcov-$KCOV_VERSION
  - ls ./target/debug/deps
  - for file in target/debug/deps/*[^\.rlib]; do mkdir -p "target/coverage/$(basename $file)"; kcov --include-pattern=${TRAVIS_BUILD_DIR}/src/ "target/coverage/$(basename $file)" "$file"; done
  - bash <(curl -s https://codecov.io/bash)
  - echo "Uploaded code coverage"