[package]
name = "simple_redis"
version = "0.1.0"
authors = ["sagie gur ari <sagiegurari@gmail.com>"]
keywords = ["redis", "cache", "pubsub", "database"]
description = "Simple redis client."
homepage = "http://github.com/sagiegurari/simple_redis"
documentation = "https://sagiegurari.github.io/simple_redis/api/simple_redis/index.html"
license = "Apache-2.0"
readme = "README.md"
include = [
    "**/*.rs",
    "docs/*",
    "Cargo.toml",
    "LICENSE",
    "README.md",
]

[dependencies]
redis = "^0.8.0"
clippy = {version = "^0.0.136", optional = true}

[features]
default = []

[badges]
travis-ci = { repository = "sagiegurari/simple_redis", branch = "master" }
appveyor = { repository = "sagiegurari/simple-redis", branch = "master", service = "github" }
coveralls = { repository = "sagiegurari/simple_redis", branch = "master", service = "github" }
