
[config]
init_task = "start-redis"
end_task = "stop-redis"
additional_profiles = [
    "ci-coverage-tasks",
    "ci-all-build-tasks",
    "ci-static-code-analysis-tasks",
    "publish-pre-cleanup"
]

[tasks.outdated]
force = true

[tasks.start-redis]
condition = { env_false = [ 'CARGO_MAKE_CI' ] }
script = [
  "echo \"Starting Redis\"",
  "redis-server --loglevel warning &",
  "sleep 1"
]

[tasks.stop-redis]
condition = { env_false = [ 'CARGO_MAKE_CI' ] }
script = [
  "echo \"Stopping any running Redis\"",
  "ps -ef | grep [r]edis-server | awk '{print $2}' | xargs kill -9 || true",
]

