
[tasks.start-redis]
script = [
  "echo \"Starting Redis\"",
  "redis-server --loglevel warning &",
  "sleep 1"
]

[tasks.stop-redis]
script = [
  "echo \"Stopping any running Redis\"",
  "ps -ef | grep [r]edis-server | awk '{print $2}' | xargs kill -9",
]

[tasks.init]
depedencies = [
  "stop-redis",
  "start-redis"
]

[tasks.end]
alias = "stop-redis"
